# syntax=docker/dockerfile:1
FROM ubuntu:22.04

ARG filename=env.txt

# install app dependencies
RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip install flask==2.1.*
RUN pip install Werkzeug==2.2.2



# copy source code for application
ONBUILD COPY ./src/ /home

EXPOSE 8000
CMD flask run --host 0.0.0.0 --port 8000